SET SERVEROUTPUT ON;

DECLARE
        WAREHOUSE1_COUNT NUMBER;
        WAREHOUSE2_COUNT NUMBER;
    BEGIN
        SELECT SUM(GOOD_COUNT) AS TOTAL
        INTO WAREHOUSE1_COUNT
        FROM WAREHOUSE1
        WHERE GOOD_ID = 28
        GROUP BY GOOD_ID;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        WAREHOUSE1_COUNT := 0;
        
        SELECT SUM(GOOD_COUNT) AS TOTAL
        INTO WAREHOUSE2_COUNT
        FROM WAREHOUSE2
        WHERE GOOD_ID = 28
        GROUP BY GOOD_ID;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        WAREHOUSE2_COUNT := 0;
        
        DBMS_OUTPUT.PUT_LINE('COUNT1=' || WAREHOUSE1_COUNT);
        
        IF WAREHOUSE1_COUNT + WAREHOUSE2_COUNT < 100 THEN
            RAISE_APPLICATION_ERROR(-20000, 'Not enough goods');        
        END IF;
    END;